platform:
  - x64

configuration:
  - Release

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 12 Win64" ..
  - cd ..

after_build:
  - ps: git show -s --pretty=format:%h-%f > git-rev.txt
  - for /f "usebackq tokens=*" %%a in (git-rev.txt) do set BUILD_NAME_UNCUT=%%a
  - set BUILD_NAME=%BUILD_NAME_UNCUT:~0,100%
  - 7z a %BUILD_NAME% .\build\release\xorer.exe

artifacts:
  - path: $(BUILD_NAME)
    name: deploy-build

deploy:
  - provider: FTP
    on:
      branch: master
    protocol: sftp
    host: archshift.com
    username: builds
    password:
      secure: 1R+NBu9p3KStaLaxGoc9xw== 
    folder: /xorer/nightly/windows/
    artifact: deploy-build
