#pragma once

enum : size_t {
    NCCH_OFFSET_MAGIC = 0x100,
    NCCH_OFFSET_EXHEADER_SIZE = 0x180,
    NCCH_OFFSET_FLAGS = 0x188,
    NCCH_OFFSET_FLAG_CRYPTO       = NCCH_OFFSET_FLAGS + 3,
    NCCH_OFFSET_FLAG_CONTENT_TYPE = NCCH_OFFSET_FLAGS + 5,
    NCCH_OFFSET_FLAG_DATA_FORMAT  = NCCH_OFFSET_FLAGS + 7,
    NCCH_OFFSET_EXEFS_OFFSET  = 0x1A0,
    NCCH_OFFSET_EXEFS_SIZE    = 0x1A4,
    NCCH_OFFSET_ROMFS_OFFSET  = 0x1B0,
    NCCH_OFFSET_ROMFS_SIZE    = 0x1B4,
    NCCH_OFFSET_EXHEADER = 0x200,
};

enum : size_t {
    FLAG_DATA = 0x1,
    FLAG_EXEC = 0x2,

    FLAG_NOROMFS  = 0x2,
    FLAG_NOCRYPTO = 0x4,
};